// app/database/seeds/ArticlesTableSeeder.php

<?php

class ArticleTableSeeder extends Seeder
{

	public function run()
	{
		DB::table('articles')->delete();
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Primer Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' => 'http://www.webbizarro.com/images/noticias/2014/02/programar-y-la-vida-webbizarro-interno_1391651697000_alarge.jpg',
			'url_video' => '<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Segundo Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' => 'http://www.webbizarro.com/images/noticias/2014/02/php-mas-rapido-webbizarro-interno_1391620688000_alarge.jpg',
			'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Tercer Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>
				
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
				'url_image' =>'http://www.webbizarro.com/images/noticias/2014/01/phalconphp-webbizarro-interno_1391208882000_alarge.jpg',
				'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Cuarto Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>
			
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
				'url_image' =>'http://www.webbizarro.com/images/noticias/2014/02/evernote-webbizarro-interno_1391463372000_alarge.jpg',
				'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Quinto Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' =>'http://www.webbizarro.com/images/noticias/2014/02/google-plus-spam-webbizarro-interna_1391565597000_alarge.jpg',
			'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Quinto Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' =>'http://www.webbizarro.com/images/noticias/2014/02/google-plus-spam-webbizarro-interna_1391565597000_alarge.jpg',
			'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Quinto Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' =>'http://www.webbizarro.com/images/noticias/2014/02/google-plus-spam-webbizarro-interna_1391565597000_alarge.jpg',
			'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Quinto Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' =>'http://www.webbizarro.com/images/noticias/2014/02/google-plus-spam-webbizarro-interna_1391565597000_alarge.jpg',
			'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
		Articles::create(array(
			'autor'     => 'John Paul',
			'titulo' => 'Mi Quinto Post',
			'texto'    => 'dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.
				. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.<br/>

			. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.dignissimos soluta dolores ducimus. Quis, ipsa, ipsum.',
			'url_image' =>'http://www.webbizarro.com/images/noticias/2014/02/google-plus-spam-webbizarro-interna_1391565597000_alarge.jpg',
			'url_video' =>'<iframe width="854" height=510 src=//www.youtube.com/embed/Ygrwb2XCp5g frameborder=0 allowfullscreen></iframe>'
		));
	}

}